package com.adufeitian.servicesystem.mybatis.mapper;

import com.adufeitian.servicesystem.mybatis.domain.ComplainInfor;
import com.adufeitian.servicesystem.mybatis.domain.ComplainInforExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComplainInforMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    long countByExample(ComplainInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int deleteByExample(ComplainInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int insert(ComplainInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int insertSelective(ComplainInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    List<ComplainInfor> selectByExample(ComplainInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    ComplainInfor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") ComplainInfor record, @Param("example") ComplainInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByExample(@Param("record") ComplainInfor record, @Param("example") ComplainInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByPrimaryKeySelective(ComplainInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByPrimaryKey(ComplainInfor record);
}