package com.adufeitian.servicesystem.mybatis.mapper;

import com.adufeitian.servicesystem.mybatis.domain.ServiceSmallCategory;
import com.adufeitian.servicesystem.mybatis.domain.ServiceSmallCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceSmallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    long countByExample(ServiceSmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int deleteByExample(ServiceSmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int insert(ServiceSmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int insertSelective(ServiceSmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    List<ServiceSmallCategory> selectByExample(ServiceSmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    ServiceSmallCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") ServiceSmallCategory record, @Param("example") ServiceSmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByExample(@Param("record") ServiceSmallCategory record, @Param("example") ServiceSmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceSmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByPrimaryKey(ServiceSmallCategory record);
}