package com.adufeitian.servicesystem.mybatis.mapper;

import com.adufeitian.servicesystem.mybatis.domain.ServiceInfor;
import com.adufeitian.servicesystem.mybatis.domain.ServiceInforExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceInforMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    long countByExample(ServiceInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int deleteByExample(ServiceInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int insert(ServiceInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int insertSelective(ServiceInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    List<ServiceInfor> selectByExample(ServiceInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    ServiceInfor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") ServiceInfor record, @Param("example") ServiceInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByExample(@Param("record") ServiceInfor record, @Param("example") ServiceInforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceInfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByPrimaryKey(ServiceInfor record);
}