package com.adufeitian.servicesystem.mybatis.mapper;

import com.adufeitian.servicesystem.mybatis.domain.ServicecLargeCategory;
import com.adufeitian.servicesystem.mybatis.domain.ServicecLargeCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServicecLargeCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    long countByExample(ServicecLargeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int deleteByExample(ServicecLargeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int insert(ServicecLargeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int insertSelective(ServicecLargeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    List<ServicecLargeCategory> selectByExample(ServicecLargeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    ServicecLargeCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") ServicecLargeCategory record, @Param("example") ServicecLargeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByExample(@Param("record") ServicecLargeCategory record, @Param("example") ServicecLargeCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByPrimaryKeySelective(ServicecLargeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    int updateByPrimaryKey(ServicecLargeCategory record);
}