package com.adufeitian.servicesystem.mybatis.domain;

import java.util.Date;

public class ComplainInfor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.com_person
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String comPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.person_phone
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String personPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.com_work
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String comWork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.com_business
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String comBusiness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.busi_phone
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String busiPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.deal_state
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String dealState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.com_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String comInfor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.deal_person
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String dealPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.deal_date
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private Date dealDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_infor.deal_ending
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String dealEnding;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.id
     *
     * @return the value of complain_infor.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.id
     *
     * @param id the value for complain_infor.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.com_person
     *
     * @return the value of complain_infor.com_person
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getComPerson() {
        return comPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.com_person
     *
     * @param comPerson the value for complain_infor.com_person
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setComPerson(String comPerson) {
        this.comPerson = comPerson == null ? null : comPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.person_phone
     *
     * @return the value of complain_infor.person_phone
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getPersonPhone() {
        return personPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.person_phone
     *
     * @param personPhone the value for complain_infor.person_phone
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setPersonPhone(String personPhone) {
        this.personPhone = personPhone == null ? null : personPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.com_work
     *
     * @return the value of complain_infor.com_work
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getComWork() {
        return comWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.com_work
     *
     * @param comWork the value for complain_infor.com_work
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setComWork(String comWork) {
        this.comWork = comWork == null ? null : comWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.com_business
     *
     * @return the value of complain_infor.com_business
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getComBusiness() {
        return comBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.com_business
     *
     * @param comBusiness the value for complain_infor.com_business
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setComBusiness(String comBusiness) {
        this.comBusiness = comBusiness == null ? null : comBusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.busi_phone
     *
     * @return the value of complain_infor.busi_phone
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getBusiPhone() {
        return busiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.busi_phone
     *
     * @param busiPhone the value for complain_infor.busi_phone
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setBusiPhone(String busiPhone) {
        this.busiPhone = busiPhone == null ? null : busiPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.deal_state
     *
     * @return the value of complain_infor.deal_state
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getDealState() {
        return dealState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.deal_state
     *
     * @param dealState the value for complain_infor.deal_state
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setDealState(String dealState) {
        this.dealState = dealState == null ? null : dealState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.com_infor
     *
     * @return the value of complain_infor.com_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getComInfor() {
        return comInfor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.com_infor
     *
     * @param comInfor the value for complain_infor.com_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setComInfor(String comInfor) {
        this.comInfor = comInfor == null ? null : comInfor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.deal_person
     *
     * @return the value of complain_infor.deal_person
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getDealPerson() {
        return dealPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.deal_person
     *
     * @param dealPerson the value for complain_infor.deal_person
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setDealPerson(String dealPerson) {
        this.dealPerson = dealPerson == null ? null : dealPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.deal_date
     *
     * @return the value of complain_infor.deal_date
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public Date getDealDate() {
        return dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.deal_date
     *
     * @param dealDate the value for complain_infor.deal_date
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setDealDate(Date dealDate) {
        this.dealDate = dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_infor.deal_ending
     *
     * @return the value of complain_infor.deal_ending
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getDealEnding() {
        return dealEnding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_infor.deal_ending
     *
     * @param dealEnding the value for complain_infor.deal_ending
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setDealEnding(String dealEnding) {
        this.dealEnding = dealEnding == null ? null : dealEnding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComplainInfor other = (ComplainInfor) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getComPerson() == null ? other.getComPerson() == null : this.getComPerson().equals(other.getComPerson()))
            && (this.getPersonPhone() == null ? other.getPersonPhone() == null : this.getPersonPhone().equals(other.getPersonPhone()))
            && (this.getComWork() == null ? other.getComWork() == null : this.getComWork().equals(other.getComWork()))
            && (this.getComBusiness() == null ? other.getComBusiness() == null : this.getComBusiness().equals(other.getComBusiness()))
            && (this.getBusiPhone() == null ? other.getBusiPhone() == null : this.getBusiPhone().equals(other.getBusiPhone()))
            && (this.getDealState() == null ? other.getDealState() == null : this.getDealState().equals(other.getDealState()))
            && (this.getComInfor() == null ? other.getComInfor() == null : this.getComInfor().equals(other.getComInfor()))
            && (this.getDealPerson() == null ? other.getDealPerson() == null : this.getDealPerson().equals(other.getDealPerson()))
            && (this.getDealDate() == null ? other.getDealDate() == null : this.getDealDate().equals(other.getDealDate()))
            && (this.getDealEnding() == null ? other.getDealEnding() == null : this.getDealEnding().equals(other.getDealEnding()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getComPerson() == null) ? 0 : getComPerson().hashCode());
        result = prime * result + ((getPersonPhone() == null) ? 0 : getPersonPhone().hashCode());
        result = prime * result + ((getComWork() == null) ? 0 : getComWork().hashCode());
        result = prime * result + ((getComBusiness() == null) ? 0 : getComBusiness().hashCode());
        result = prime * result + ((getBusiPhone() == null) ? 0 : getBusiPhone().hashCode());
        result = prime * result + ((getDealState() == null) ? 0 : getDealState().hashCode());
        result = prime * result + ((getComInfor() == null) ? 0 : getComInfor().hashCode());
        result = prime * result + ((getDealPerson() == null) ? 0 : getDealPerson().hashCode());
        result = prime * result + ((getDealDate() == null) ? 0 : getDealDate().hashCode());
        result = prime * result + ((getDealEnding() == null) ? 0 : getDealEnding().hashCode());
        return result;
    }
}