package com.adufeitian.servicesystem.mybatis.domain;

public class ServiceSmallCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_small_category.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_small_category.sestem_id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String sestemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_small_category.system_lc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String systemLcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_small_category.system_sc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String systemScName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_small_category.description
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_small_category.id
     *
     * @return the value of service_small_category.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_small_category.id
     *
     * @param id the value for service_small_category.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_small_category.sestem_id
     *
     * @return the value of service_small_category.sestem_id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getSestemId() {
        return sestemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_small_category.sestem_id
     *
     * @param sestemId the value for service_small_category.sestem_id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setSestemId(String sestemId) {
        this.sestemId = sestemId == null ? null : sestemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_small_category.system_lc_name
     *
     * @return the value of service_small_category.system_lc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getSystemLcName() {
        return systemLcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_small_category.system_lc_name
     *
     * @param systemLcName the value for service_small_category.system_lc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setSystemLcName(String systemLcName) {
        this.systemLcName = systemLcName == null ? null : systemLcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_small_category.system_sc_name
     *
     * @return the value of service_small_category.system_sc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getSystemScName() {
        return systemScName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_small_category.system_sc_name
     *
     * @param systemScName the value for service_small_category.system_sc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setSystemScName(String systemScName) {
        this.systemScName = systemScName == null ? null : systemScName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_small_category.description
     *
     * @return the value of service_small_category.description
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_small_category.description
     *
     * @param description the value for service_small_category.description
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ServiceSmallCategory other = (ServiceSmallCategory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSestemId() == null ? other.getSestemId() == null : this.getSestemId().equals(other.getSestemId()))
            && (this.getSystemLcName() == null ? other.getSystemLcName() == null : this.getSystemLcName().equals(other.getSystemLcName()))
            && (this.getSystemScName() == null ? other.getSystemScName() == null : this.getSystemScName().equals(other.getSystemScName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSestemId() == null) ? 0 : getSestemId().hashCode());
        result = prime * result + ((getSystemLcName() == null) ? 0 : getSystemLcName().hashCode());
        result = prime * result + ((getSystemScName() == null) ? 0 : getSystemScName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}