package com.adufeitian.servicesystem.mybatis.domain;

public class ServiceInfor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_infor.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_infor.system_lc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String systemLcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_infor.system_sc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String systemScName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_infor.simple_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String simpleInfor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_infor.charge
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String charge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_infor.id
     *
     * @return the value of service_infor.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_infor.id
     *
     * @param id the value for service_infor.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_infor.system_lc_name
     *
     * @return the value of service_infor.system_lc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getSystemLcName() {
        return systemLcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_infor.system_lc_name
     *
     * @param systemLcName the value for service_infor.system_lc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setSystemLcName(String systemLcName) {
        this.systemLcName = systemLcName == null ? null : systemLcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_infor.system_sc_name
     *
     * @return the value of service_infor.system_sc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getSystemScName() {
        return systemScName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_infor.system_sc_name
     *
     * @param systemScName the value for service_infor.system_sc_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setSystemScName(String systemScName) {
        this.systemScName = systemScName == null ? null : systemScName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_infor.simple_infor
     *
     * @return the value of service_infor.simple_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getSimpleInfor() {
        return simpleInfor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_infor.simple_infor
     *
     * @param simpleInfor the value for service_infor.simple_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setSimpleInfor(String simpleInfor) {
        this.simpleInfor = simpleInfor == null ? null : simpleInfor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_infor.charge
     *
     * @return the value of service_infor.charge
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_infor.charge
     *
     * @param charge the value for service_infor.charge
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setCharge(String charge) {
        this.charge = charge == null ? null : charge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ServiceInfor other = (ServiceInfor) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSystemLcName() == null ? other.getSystemLcName() == null : this.getSystemLcName().equals(other.getSystemLcName()))
            && (this.getSystemScName() == null ? other.getSystemScName() == null : this.getSystemScName().equals(other.getSystemScName()))
            && (this.getSimpleInfor() == null ? other.getSimpleInfor() == null : this.getSimpleInfor().equals(other.getSimpleInfor()))
            && (this.getCharge() == null ? other.getCharge() == null : this.getCharge().equals(other.getCharge()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_infor
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSystemLcName() == null) ? 0 : getSystemLcName().hashCode());
        result = prime * result + ((getSystemScName() == null) ? 0 : getSystemScName().hashCode());
        result = prime * result + ((getSimpleInfor() == null) ? 0 : getSimpleInfor().hashCode());
        result = prime * result + ((getCharge() == null) ? 0 : getCharge().hashCode());
        return result;
    }
}