package com.adufeitian.servicesystem.mybatis.domain;

import java.util.ArrayList;
import java.util.List;

public class ServiceSmallCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public ServiceSmallCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSestemIdIsNull() {
            addCriterion("sestem_id is null");
            return (Criteria) this;
        }

        public Criteria andSestemIdIsNotNull() {
            addCriterion("sestem_id is not null");
            return (Criteria) this;
        }

        public Criteria andSestemIdEqualTo(String value) {
            addCriterion("sestem_id =", value, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdNotEqualTo(String value) {
            addCriterion("sestem_id <>", value, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdGreaterThan(String value) {
            addCriterion("sestem_id >", value, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdGreaterThanOrEqualTo(String value) {
            addCriterion("sestem_id >=", value, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdLessThan(String value) {
            addCriterion("sestem_id <", value, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdLessThanOrEqualTo(String value) {
            addCriterion("sestem_id <=", value, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdLike(String value) {
            addCriterion("sestem_id like", value, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdNotLike(String value) {
            addCriterion("sestem_id not like", value, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdIn(List<String> values) {
            addCriterion("sestem_id in", values, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdNotIn(List<String> values) {
            addCriterion("sestem_id not in", values, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdBetween(String value1, String value2) {
            addCriterion("sestem_id between", value1, value2, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSestemIdNotBetween(String value1, String value2) {
            addCriterion("sestem_id not between", value1, value2, "sestemId");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameIsNull() {
            addCriterion("system_lc_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameIsNotNull() {
            addCriterion("system_lc_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameEqualTo(String value) {
            addCriterion("system_lc_name =", value, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameNotEqualTo(String value) {
            addCriterion("system_lc_name <>", value, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameGreaterThan(String value) {
            addCriterion("system_lc_name >", value, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_lc_name >=", value, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameLessThan(String value) {
            addCriterion("system_lc_name <", value, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameLessThanOrEqualTo(String value) {
            addCriterion("system_lc_name <=", value, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameLike(String value) {
            addCriterion("system_lc_name like", value, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameNotLike(String value) {
            addCriterion("system_lc_name not like", value, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameIn(List<String> values) {
            addCriterion("system_lc_name in", values, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameNotIn(List<String> values) {
            addCriterion("system_lc_name not in", values, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameBetween(String value1, String value2) {
            addCriterion("system_lc_name between", value1, value2, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemLcNameNotBetween(String value1, String value2) {
            addCriterion("system_lc_name not between", value1, value2, "systemLcName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameIsNull() {
            addCriterion("system_sc_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemScNameIsNotNull() {
            addCriterion("system_sc_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemScNameEqualTo(String value) {
            addCriterion("system_sc_name =", value, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameNotEqualTo(String value) {
            addCriterion("system_sc_name <>", value, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameGreaterThan(String value) {
            addCriterion("system_sc_name >", value, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_sc_name >=", value, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameLessThan(String value) {
            addCriterion("system_sc_name <", value, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameLessThanOrEqualTo(String value) {
            addCriterion("system_sc_name <=", value, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameLike(String value) {
            addCriterion("system_sc_name like", value, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameNotLike(String value) {
            addCriterion("system_sc_name not like", value, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameIn(List<String> values) {
            addCriterion("system_sc_name in", values, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameNotIn(List<String> values) {
            addCriterion("system_sc_name not in", values, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameBetween(String value1, String value2) {
            addCriterion("system_sc_name between", value1, value2, "systemScName");
            return (Criteria) this;
        }

        public Criteria andSystemScNameNotBetween(String value1, String value2) {
            addCriterion("system_sc_name not between", value1, value2, "systemScName");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_small_category
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 18 11:56:58 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_small_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}