package com.adufeitian.servicesystem.mybatis.domain;

public class ServicecLargeCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicec_large_category.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicec_large_category.system_id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicec_large_category.service_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicec_large_category.description
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicec_large_category.id
     *
     * @return the value of servicec_large_category.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicec_large_category.id
     *
     * @param id the value for servicec_large_category.id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicec_large_category.system_id
     *
     * @return the value of servicec_large_category.system_id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicec_large_category.system_id
     *
     * @param systemId the value for servicec_large_category.system_id
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId == null ? null : systemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicec_large_category.service_name
     *
     * @return the value of servicec_large_category.service_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicec_large_category.service_name
     *
     * @param serviceName the value for servicec_large_category.service_name
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicec_large_category.description
     *
     * @return the value of servicec_large_category.description
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicec_large_category.description
     *
     * @param description the value for servicec_large_category.description
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ServicecLargeCategory other = (ServicecLargeCategory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSystemId() == null ? other.getSystemId() == null : this.getSystemId().equals(other.getSystemId()))
            && (this.getServiceName() == null ? other.getServiceName() == null : this.getServiceName().equals(other.getServiceName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicec_large_category
     *
     * @mbg.generated Thu Jun 18 11:56:58 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSystemId() == null) ? 0 : getSystemId().hashCode());
        result = prime * result + ((getServiceName() == null) ? 0 : getServiceName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}